#!/usr/bin/env zsh
export ANSIBLE_HOME=$HOME/repos/ansible
export ANSIBLE_COLLECTIONS_PATH=$HOME/repos/ansible/collections
export ANSIBLE_DEV_HOME=$ANSIBLE_COLLECTIONS_PATH/ansible_collections/ansible
export ANSIBLE_ROLES_PATH=$ANSIBLE_COLLECTIONS_PATH/ansible_collections/cisco/nd/tests/integration/targets
export PYTHONPATH=$ANSIBLE_COLLECTIONS_PATH:$ANSIBLE_COLLECTIONS_PATH/ansible_collections:$ANSIBLE_DEV_HOME:$ANSIBLE_COLLECTIONS_PATH/ansible_collections/cisco/nd
export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=1200
export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=1200
